### ISSUE TITLE
babel - webpack 4 export default issue

### ISSUE THREAD

**Issue by kouts** [ractivejs/ractive-bin-loader#1]
When using babel + webpack 3 in order for export default to work correctly I used ```babel-plugin-add-module-exports```
This no longer works with webpack 4 so I have to use
```import(/* webpackChunkName: "component" */'./component.ractive.html').then(module => module.default)```

Is there any solution to this?

**Comment by evs-chris** [comment]
I haven't messed with webpack 4 yet, but I'll see if I can get it set up to look. Is ractive processing the file first? If so, what the bin loader is doing really _shouldn't_ affect anything else cause its output should just look like a plain old module.

**Comment by kouts** [comment]
I'll try to make a basic github repo to demonstrate.

**Comment by kouts** [comment]
I have created a test repo here: https://github.com/kouts/ractive-loader-test
You can view the issue in https://github.com/kouts/ractive-loader-test/blob/master/src/main.js

**Comment by evs-chris** [comment]
Looking at the changes in webpack, it looks like this is a breaking change decision in order to be in line with proposed spec - when you `import()` you always get the module namespace, so you have to grab whatever you need off the result. I'm not really sure if there's any way to alleviate that from the loader from what I found in the related webpack issues. One thing we _could_ do would be to let ractive check for `default` members on non-instances and use those automatically. If you needed a named export, you'd still have to pull it in from the namespace.

**Comment by kouts** [comment]
Thanks @evs-chris that's a good idea if you can implement it in Ractive, up to you!
Thanks as always for your help.

**Comment by evs-chris** [comment]
This is now supported from the Ractive side. Thanks!
